### ISSUE TITLE
How do you get images?

### ISSUE THREAD

**Issue by yagudaev** [uxiew/epub2MD#19]
Hi thanks again for building this great library 🙏.

I'm trying to figure out how to get images, is it possible through the library right now? Or do I need to use another library like epub2 for that?

**Comment by uxiew** [comment]
the `EpubObject` object has sections array,each of them has a `toHtmlObjects` method, read more from the [README](https://github.com/uxiew/epub2MD?tab=readme-ov-file#epubobject). comment here if you get any problems.
